[package]
name = "problem05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
range-ext = "0.3.0"
regex = "1.10.2"
regexp = "0.3.2"
